fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
  symlinks:
    tomcat: "#{source_dir}"
